// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: nirvana.proto

package nirvana

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateExceptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Attributes *ExceptionAttributes `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *CreateExceptionRequest) Reset() {
	*x = CreateExceptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nirvana_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExceptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExceptionRequest) ProtoMessage() {}

func (x *CreateExceptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nirvana_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExceptionRequest.ProtoReflect.Descriptor instead.
func (*CreateExceptionRequest) Descriptor() ([]byte, []int) {
	return file_nirvana_proto_rawDescGZIP(), []int{0}
}

func (x *CreateExceptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExceptionRequest) GetAttributes() *ExceptionAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CreateExceptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateExceptionResponse) Reset() {
	*x = CreateExceptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nirvana_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExceptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExceptionResponse) ProtoMessage() {}

func (x *CreateExceptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nirvana_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExceptionResponse.ProtoReflect.Descriptor instead.
func (*CreateExceptionResponse) Descriptor() ([]byte, []int) {
	return file_nirvana_proto_rawDescGZIP(), []int{1}
}

type CheckExceptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Attributes *ExceptionAttributes `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *CheckExceptionRequest) Reset() {
	*x = CheckExceptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nirvana_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckExceptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExceptionRequest) ProtoMessage() {}

func (x *CheckExceptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nirvana_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExceptionRequest.ProtoReflect.Descriptor instead.
func (*CheckExceptionRequest) Descriptor() ([]byte, []int) {
	return file_nirvana_proto_rawDescGZIP(), []int{2}
}

func (x *CheckExceptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckExceptionRequest) GetAttributes() *ExceptionAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CheckExceptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *CheckExceptionResponse) Reset() {
	*x = CheckExceptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nirvana_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckExceptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExceptionResponse) ProtoMessage() {}

func (x *CheckExceptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nirvana_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExceptionResponse.ProtoReflect.Descriptor instead.
func (*CheckExceptionResponse) Descriptor() ([]byte, []int) {
	return file_nirvana_proto_rawDescGZIP(), []int{3}
}

func (x *CheckExceptionResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ExceptionAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId *string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	Amount   *int64  `protobuf:"varint,2,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
}

func (x *ExceptionAttributes) Reset() {
	*x = ExceptionAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nirvana_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExceptionAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExceptionAttributes) ProtoMessage() {}

func (x *ExceptionAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_nirvana_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExceptionAttributes.ProtoReflect.Descriptor instead.
func (*ExceptionAttributes) Descriptor() ([]byte, []int) {
	return file_nirvana_proto_rawDescGZIP(), []int{4}
}

func (x *ExceptionAttributes) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *ExceptionAttributes) GetAmount() int64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

var File_nirvana_proto protoreflect.FileDescriptor

var file_nirvana_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6e, 0x69, 0x72, 0x76, 0x61, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x22, 0x6a, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78,
	0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x69, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x0a,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x45, 0x78, 0x63, 0x65, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x0a,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x22, 0x2e, 0x0a, 0x16, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x6d, 0x0a, 0x13, 0x45, 0x78,
	0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x12, 0x20, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xb6, 0x01, 0x0a, 0x07, 0x4e, 0x69,
	0x72, 0x76, 0x61, 0x6e, 0x61, 0x12, 0x56, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45,
	0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a,
	0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45,
	0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45,
	0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x69,
	0x72, 0x76, 0x61, 0x6e, 0x61, 0x3b, 0x6e, 0x69, 0x72, 0x76, 0x61, 0x6e, 0x61, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nirvana_proto_rawDescOnce sync.Once
	file_nirvana_proto_rawDescData = file_nirvana_proto_rawDesc
)

func file_nirvana_proto_rawDescGZIP() []byte {
	file_nirvana_proto_rawDescOnce.Do(func() {
		file_nirvana_proto_rawDescData = protoimpl.X.CompressGZIP(file_nirvana_proto_rawDescData)
	})
	return file_nirvana_proto_rawDescData
}

var file_nirvana_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_nirvana_proto_goTypes = []any{
	(*CreateExceptionRequest)(nil),  // 0: control.CreateExceptionRequest
	(*CreateExceptionResponse)(nil), // 1: control.CreateExceptionResponse
	(*CheckExceptionRequest)(nil),   // 2: control.CheckExceptionRequest
	(*CheckExceptionResponse)(nil),  // 3: control.CheckExceptionResponse
	(*ExceptionAttributes)(nil),     // 4: control.ExceptionAttributes
}
var file_nirvana_proto_depIdxs = []int32{
	4, // 0: control.CreateExceptionRequest.attributes:type_name -> control.ExceptionAttributes
	4, // 1: control.CheckExceptionRequest.attributes:type_name -> control.ExceptionAttributes
	0, // 2: control.Nirvana.CreateException:input_type -> control.CreateExceptionRequest
	2, // 3: control.Nirvana.CheckException:input_type -> control.CheckExceptionRequest
	1, // 4: control.Nirvana.CreateException:output_type -> control.CreateExceptionResponse
	3, // 5: control.Nirvana.CheckException:output_type -> control.CheckExceptionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nirvana_proto_init() }
func file_nirvana_proto_init() {
	if File_nirvana_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nirvana_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateExceptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nirvana_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateExceptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nirvana_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CheckExceptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nirvana_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CheckExceptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nirvana_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ExceptionAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_nirvana_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nirvana_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nirvana_proto_goTypes,
		DependencyIndexes: file_nirvana_proto_depIdxs,
		MessageInfos:      file_nirvana_proto_msgTypes,
	}.Build()
	File_nirvana_proto = out.File
	file_nirvana_proto_rawDesc = nil
	file_nirvana_proto_goTypes = nil
	file_nirvana_proto_depIdxs = nil
}
