version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: nirvana-dbb
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: nirvana1
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
